java:
  build: java
  volumes:
    - /opt/java-bin

tomcat:
  build: tomcat
  volumes:
    - /tomcat-bin

eclipsedata:
  build: eclipse-data
  volumes:
    - /workspace

eclipse:
  build: eclipse-others
  volumes_from:
    - java
    - tomcat
    - eclipsedata
  ports:
    - "8080:8080"
    - "5900:5900"
