java:
  build: java
  volumes:
    - /opt/java-bin

tomcat:
  build: tomcat
  volumes:
    - /tomcat-bin

eclipsedata:
  build: eclipse-data
  volumes:
    - /workspace

eclipse:
  build: eclipse-linux
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
  volumes_from:
    - java
    - tomcat
    - eclipsedata
  environment:
    - DISPLAY
  ports:
    - 8080
