java:
  build: java
  volumes:
    - /opt/java-bin 

tomcat:
  build: tomcat
  volumes:
    - /tomcat-bin

process:
  build: process
  volumes_from:
    - java
    - tomcat
  ports:
    - 8080
  environment:
    - JAVA_HOME=/opt/java-bin
