java:
  build: java
  volumes:
    - /opt/java-bin

mysqldata:
  image: busybox:latest
  volumes:
    - /var/lib/mysql

mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=AezohghooNgaegh8ei2jabib2nuj9yoe
    - MYSQL_DATABASE=pizzaiolo2
  volumes_from:
    - mysqldata

tomcat:
  build: tomcat
  volumes:
    - /tomcat-bin

maven:
  build: maven
  volumes:
    - /apache-maven

eclipsedata:
  build: eclipse-data
  volumes:
    - /workspace

eclipse:
  image: 192.168.1.2:5000/eclipse
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
  volumes_from:
    - java
    - tomcat
    - eclipsedata
    - maven
  environment:
    - DISPLAY
  ports:
    - "8080"
  links:
    - mysql:mysql
