java:
  build: java
  volumes:
    - /opt/java-bin
  labels:
    - "nature=binaries"

mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=AezohghooNgaegh8ei2jabib2nuj9yoe
    - MYSQL_DATABASE=pizzaiolo2
  labels:
    - "nature=process"
    - "nature=data"

tomcat:
  build: tomcat
  volumes:
    - /tomcat-bin
  labels:
    - "nature=binaries"

maven:
  build: maven
  volumes:
    - /apache-maven
  labels:
    - "nature=binaries"

eclipsedata:
  build: eclipse-data
  volumes:
    - /workspace
  labels:
    - "nature=data"

eclipse:
  build: eclipse
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
  volumes_from:
    - java
    - tomcat
    - eclipsedata
    - maven
  environment:
    - DISPLAY
  ports:
    - "8080"
  links:
    - mysql:mysql
  labels:
    - "nature=process"
